version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
# docker run --name mongoCurriculum -v /Curriculum/app/datadir:/data/db -d mongo #